### ISSUE TITLE
RAM size check with hardcoded value prevents fuzzing with WHV/KVM backend

### ISSUE THREAD

**Issue by 1ndahous3** [0vercl0k/wtf#111]
I have 32GB RAM available on my machine and when I trying to fuzz via the whv/kvm backend I got an error:
```
D:\wtf_fuzzing\targets>..\wtf.exe fuzz --backend=whv --name ioctl --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
The dump size (5368709120) is too large.
Failed to initialize the RAM
Failed to PopulateMemory
Backend failed initialization.
```

I think the better way is remove extra check:
https://github.com/0vercl0k/wtf/blob/bfe47f68f89cc64027abcdf362a7f4335451ce98/src/wtf/ram.h#L41
https://github.com/0vercl0k/wtf/blob/bfe47f68f89cc64027abcdf362a7f4335451ce98/src/wtf/ram.h#L114-L117

And let execution fail on `VirtualAlloc()`/`mmap()` if the system is low on memory (it works for me).

**Comment by 0vercl0k** [comment]
Heh, fair enough!

Cheers
