### ISSUE TITLE
Unable to fuzz with WHV backend

### ISSUE THREAD

**Issue by 1ndahous3** [0vercl0k/wtf#112]
When I run server and one fuzzing node with whv backend, I got an error:

Server:
```
D:\wtf_fuzzing\targets>..\wtf.exe master --name ioctl --max_len=1028 --runs=10000000 --target .
Seeded with 1892113798163204355
Iterating through the corpus..
Sorting through the 127 entries..
Running server on tcp://localhost:31337..
#0 cov: 0 (+0) corp: 0 (0.0b) exec/s: -nan (1 nodes) lastcov: 6.0s crash: 0 timeout: 0 cr3: 0 uptime: 6.0s                                                                   The corpus is empty, exiting
```

Fuzzing node:
```
D:\wtf_fuzzing\targets>..\wtf.exe fuzz --backend=whv --name ioctl --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
Resolved breakpoint 0x7ffec31e3ff4 at GPA 0xffbaff4 aka HVA 0x19c4618dff4
Resolved breakpoint 0xfffff8012755c6e0 at GPA 0x10055c6e0 aka HVA 0x19c4617f6e0
Resolved breakpoint 0xfffff801274a1e63 at GPA 0x1004a1e63 aka HVA 0x19c4618fe63
Resolved breakpoint 0xfffff80127762230 at GPA 0x100762230 aka HVA 0x19c46181230
Resolved breakpoint 0xfffff8012761fab0 at GPA 0x10061fab0 aka HVA 0x19c46189ab0
Dialing to tcp://localhost:31337/..
Could not receive size (-1)
Receive failed
#127 cov: 0 exec/s: 31.8 lastcov: 4.0s crash: 0 timeout: 0 cr3: 0 uptime: 4.0s
```

Note: the state was dumped from VMWare and fuzzing performs normally with `--backend=bochscpu`

**Comment by 0vercl0k** [comment]
If you look closely at the stats output, you can notice that you have `cov: 0` which indicates that either the 127 inputs in your corpus triggered 0 useful coverage (which is a problem) or that you haven't generated the `.cov` files so that `wtf` knows when you hit code that is interesting to you.

The error will go away once you solve that!

Cheers

**Comment by 1ndahous3** [comment]
> If you look closely at the stats output, you can notice that you have `cov: 0` which indicates that either the 127 inputs in your corpus triggered 0 useful coverage (which is a problem) or that you haven't generated the `.cov` files so that `wtf` knows when you hit code that is interesting to you.
> 
> The error will go away once you solve that!
> 
> Cheers

That's interesting. I tried fuzzing first with bochscpu, then stopping it and using the generated `aggregate.cov` to run the WHV variant. Now the execution continues, but the coverage counter does not increase:

```
D:\wtf_fuzzing\targets>..\wtf.exe fuzz --backend=whv --name ioctl --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
/!\ The file size (5368709120) is larger than what the author tested, running at your own risk :)!
Setting debug register status to zero.
Setting debug register status to zero.
Resolved breakpoint 0x7ffec31e3ff4 at GPA 0xffbaff4 aka HVA 0x1882b45eff4
Resolved breakpoint 0xfffff8012755c6e0 at GPA 0x10055c6e0 aka HVA 0x1882b46e6e0
Resolved breakpoint 0xfffff801274a1e63 at GPA 0x1004a1e63 aka HVA 0x1882b462e63
Resolved breakpoint 0xfffff80127762230 at GPA 0x100762230 aka HVA 0x1882b468230
Resolved breakpoint 0xfffff8012761fab0 at GPA 0x10061fab0 aka HVA 0x1882b466ab0
Dialing to tcp://localhost:31337/..
#1223 cov: 0 exec/s: 122.3 lastcov: 10.0s crash: 0 timeout: 0 cr3: 146 uptime: 10.0s
#3085 cov: 0 exec/s: 154.2 lastcov: 20.0s crash: 0 timeout: 0 cr3: 361 uptime: 20.0s
[...]
#653451 cov: 0 exec/s: 186.8 lastcov: 58.3min crash: 0 timeout: 0 cr3: 80146 uptime: 58.3min
#655421 cov: 0 exec/s: 186.8 lastcov: 58.5min crash: 0 timeout: 0 cr3: 80358 uptime: 58.5min
```

And just run one case:
```
D:\wtf_fuzzing\targets>..\wtf.exe run --backend=whv --name ioctl --limit 10000000 --input outputs\031a32557dd7304bb67bcc52257c6aed --state=state --trace-type=cov
Initializing the debugger instance.. (this takes a bit of time)
/!\ The file size (5368709120) is larger than what the author tested, running at your own risk :)!
Setting debug register status to zero.
Setting debug register status to zero.
Resolved breakpoint 0x7ffec31e3ff4 at GPA 0xffbaff4 aka HVA 0x19078648ff4
Resolved breakpoint 0xfffff8012755c6e0 at GPA 0x10055c6e0 aka HVA 0x1907863e6e0
Resolved breakpoint 0xfffff801274a1e63 at GPA 0x1004a1e63 aka HVA 0x19078640e63
Resolved breakpoint 0xfffff80127762230 at GPA 0x100762230 aka HVA 0x19078650230
Resolved breakpoint 0xfffff8012761fab0 at GPA 0x10061fab0 aka HVA 0x1907864aab0
Trace file D:\wtf_fuzzing\targets\031a32557dd7304bb67bcc52257c6aed.trace
Running outputs\031a32557dd7304bb67bcc52257c6aed
--------------------------------------------------
Run stats:
Dirty pages: 225280 bytes, 55 pages, 0 MB
Page-faults: 0
    VMExits: 56
#1 cov: 0 exec/s: 0.5 lastcov: 2.0s crash: 0 timeout: 0 cr3: 0 uptime: 2.0s
```

Same effect with KVM on Linux.

**Comment by 0vercl0k** [comment]
I think there's something you are misunderstanding - in order for the
hypervisor backend to be able to collect coverage, they simply set software
breakpoints on the beginning of every basic block. Once the code reaches
those basic blocks, it triggers an exception that they handle, removes the
breakpoint and carries on.

This means that somehow you need to tell them where the code they should
set breakpoints at. One easy way to do that, is to use
the gen_coveragefile_ida.py script in the scripts folder on the modules you
want to get coverage from. This generates .cov files (that are different
from the aggregate.cov; maybe I should have used a different extension to
make it less confusing, ugh). Then you put all those .cov files into the
'coverage' folder of your target folder. I just realized it is not
documented in the README, I need to change that. You can check out
https://doar-e.github.io/blog/2021/07/15/building-a-new-snapshot-fuzzer-fuzzing-ida/
where I talk about it (grep gen_coveragefile_ida.py).

When you run the fuzzing w/ the hypervisors, it will tell you how many
'code breakpoints' it applied (you can see it in some of the GIFs); in your
output you don't see that.

Cheers

**Comment by 0vercl0k** [comment]
Also, bochscpu gets full code coverage because the emulator exposes a
really easy way to get a callback at every instructions, so that's why it
automatically works there, but not with the other backends :)

**Comment by 1ndahous3** [comment]
ah, shame on me, I skipped that part of the article and forgot to come back to it later :(
Thanks for the hint!

I think it would be nice to also check for a non-empty 'coverage' folder if the WHV/KVM backend is selected. At least as warning.

**Comment by 1ndahous3** [comment]
So in my case (fuzzing driver ioctls with buffers) I think I should collect coverage of the kernel (ntoskrnl.exe) and all the drivers that the thread might hit, because nobody knows all kernel modules to be affected starting from target driver.

**Comment by 0vercl0k** [comment]
> I think it would be nice to also check for a non-empty 'coverage' folder if the WHV/KVM backend is selected. At least as warning.

I love that, filed #117 to implement that!


> So in my case (fuzzing driver ioctls + buffers) I think I should collect coverage of the kernel (ntoskrnl.exe) and all the drivers that the thread might hit, because nobody knows all kernel modules to be affected starting from target driver.

My 2c: I would start w/ `ntoskrnl` + the target driver you have in mind (assuming not `nt`). You could in theory try to instrument all the things, but I am not too sure how much value you'll get from that.

Cheers

**Comment by 0vercl0k** [comment]
Just circling back to know if your issue is solved @1ndahous3 ? I'll close the issue in a few days in I don't hear back 🙂

Cheers

**Comment by 1ndahous3** [comment]
@0vercl0k sorry for the delay, right now I decided to focus on fuzzing with bochscpu and improve my skills with deterministic algorithms. I will return to WHV/KVM backends a bit later)

**Comment by 0vercl0k** [comment]
No worries at all!

**Comment by 0vercl0k** [comment]
Are you okay if I close this issue? Feel free to re-open it when you get back to it!

Cheers

**Comment by 1ndahous3** [comment]
@0vercl0k sure!
