### ISSUE TITLE
`Failed to insert testcase` if `--max_len` is big

### ISSUE THREAD

**Issue by donghyunlee00** [0vercl0k/wtf#120]
--max_len 80000

![image](https://user-images.githubusercontent.com/26313346/184836551-1f3da320-e915-4f43-bcdc-2f28200d4f92.png)

--max_len 1028

![image](https://user-images.githubusercontent.com/26313346/184837056-7fe183a4-d869-4adc-b5c4-909259310141.png)

Is this intended?

**Comment by 0vercl0k** [comment]
The fuzzing module decides what is a size that is too large or not; in this
case you can see the check here:
https://github.com/0vercl0k/wtf/blob/main/src/wtf/fuzzer_hevd.cc#L29.

Cheers
