### ISSUE TITLE
WHvRunVpExitReasonInvalidVpRegisterValue

### ISSUE THREAD

**Issue by 0vercl0k** [0vercl0k/wtf#15]
@und3ath shared with me a dump that wouldn't load under `whv` with the following error code:

```
WHvRunVirtualProcessor exited with WHvRunVpExitReasonInvalidVpRegisterValue
```

I've dealt a lot with those in the past and, in my experience, it's usually a segment register being not right or the `xcr0` register. After looking at the `regs.json` file I noticed this:
```json
    "ss": {
        "present": true,
        "selector": "0x18",
        "base": "0x0",
        "limit": "0x0",
        "attr": "0x493"
    },
```

Setting a proper `limit` fixes the issue:

```diff
diff --git a/state/regs.json b/state/regs.json
index ad6760c..11d215e 100644
--- a/state/regs.json
+++ b/state/regs.json
@@ -35,7 +35,7 @@
         "present": true,
         "selector": "0x18",
         "base": "0x0",
-        "limit": "0x0",
+        "limit": "0xffffffff",
         "attr": "0x493"
     },
     "ds": {
```

I'm filling this issue in case other people run into this (including me when I forget all about it) 😁

Cheers

**Comment by lic-gallardo** [comment]
> @und3ath shared with me a dump that wouldn't load under `whv` with the following error code:
> 
> ```
> WHvRunVirtualProcessor exited with WHvRunVpExitReasonInvalidVpRegisterValue
> ```
> 
> I've dealt a lot with those in the past and, in my experience, it's usually a segment register being not right or the `xcr0` register. After looking at the `regs.json` file I noticed this:
> 
> ```json
>     "ss": {
>         "present": true,
>         "selector": "0x18",
>         "base": "0x0",
>         "limit": "0x0",
>         "attr": "0x493"
>     },
> ```
> 
> Setting a proper `limit` fixes the issue:
> 
> ```diff
> diff --git a/state/regs.json b/state/regs.json
> index ad6760c..11d215e 100644
> --- a/state/regs.json
> +++ b/state/regs.json
> @@ -35,7 +35,7 @@
>          "present": true,
>          "selector": "0x18",
>          "base": "0x0",
> -        "limit": "0x0",
> +        "limit": "0xffffffff",
>          "attr": "0x493"
>      },
>      "ds": {
> ```
> 
> I'm filling this issue in case other people run into this (including me when I forget all about it) 😁
> 
> Cheers
src/libs/json/test/thirdparty/Fuzzer/test/no-coverage/CMakeLists.txt
