### ISSUE TITLE
Server not creating outputs

### ISSUE THREAD

**Issue by Flerov** [0vercl0k/wtf#153]
I had a hard time getting bochscpu ready. The provided build-bochscpu.bat was not working for me.
So I did it myself and copied the directories bochscpu /-build / -ffi into the bxbuild-win folder.

I can start the server and the fuzzer like shown in the example. But the server is not saving into outputs/
The server shows me a lot of crashes but I dont see any in the crashes/ folder.

What did I do wrong?
Help much appreciated I'm stuck on here for a couple of days thanks alot!
![Screenshot (27)](https://user-images.githubusercontent.com/30928491/212045303-b8ee58fe-2d16-424c-90dd-50cb5db0213d.png)

**Comment by 0vercl0k** [comment]
What about the crashes folder? If not that sounds like a bug (not
your fault!) and will check it out tonight!

Cheers

**Comment by Flerov** [comment]
Thanks for the fast replies.
I realised that everything was setup properly except of the point I took my Snapshot.
Would you mind giving me some insight at what point it is best to take a Snapshot.
I was following your readme to HEVD and took the Snapshot (like in your pictures) right before the call (right before stepping over) hevd_client!_imp_DeviceIoControl then i switched contect back to kernel and took the dump.
I'm also pretty sure that I was not inside of the break-handler since I was breaking at hevd_client!main and stepped through till right before the DeviceIo call. Made me confused on how it went wrong.

**Comment by 0vercl0k** [comment]
Okay so I just looked at this. Here's what I've done:
- I downloaded the 7z archive with the HEVD example (I noticed a typo in the `server.bat` script actually, so fixed that, and also modified the `fuzz-bxcpu` to enable the new `--edges` option). It seems to run fine on my end:
```
Saving output in .\outputs\0dc68b253aaf6886f031fcfad031cbed
Saving crash in .\crashes\crash-0x50-0xffffffffffdde340-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xfffffffeffdde337-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xffffffffffdde637-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xffffff0dffdde337-0x0-0xffffbf84fb10e780-0x2-0x0
Saving output in .\outputs\b192415a46b4b52cd902081d27eb07f0
Saving output in .\outputs\4275bb5cdef5d27f56c1b4502066b3cc
Saving output in .\outputs\dd9a8d7f4cd071c5bf74f195b62f3966
Saving crash in .\crashes\crash-0x50-0xffffffe3ddff37ff-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xffffffffffdda337-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xffffffffabdde337-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xffffffffddff37e3-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xffffff94ffdde337-0x0-0xffffbf84fb10e780-0x2-0x0
Saving crash in .\crashes\crash-0x50-0xffffffffffdde341-0x0-0xffffbf84fb10e780-0x2-0x0
```
- Now, it seems like you might be providing your own dump. So I also reviewed the code that handles crashes. The client part is in [client.cc here](https://github.com/0vercl0k/wtf/blob/841ba28236690ad8b08f4e46886ee18036eecba8/src/wtf/client.cc#L240-L255), and on the server-side in [server.h here](https://github.com/0vercl0k/wtf/blob/841ba28236690ad8b08f4e46886ee18036eecba8/src/wtf/server.h#L896-L917):
```
    //
    // If the client reported a crash, let's check if it has a name, if so
    // we'll save it in the crashes folder.
    //

    if (const auto &Crash = std::get_if<Crash_t>(&Result)) {
      if (Crash->CrashName.size() > 0) {
        const auto &OutputPath = Opts_.CrashesPath / Crash->CrashName;
        const auto &Success =
            SaveFile(OutputPath, (uint8_t *)ReceivedTestcase.data(),
                     ReceivedTestcase.size());
        if (!Success) {
          fmt::print("Could not create the destination file.\n");
          return false;
        }

        const bool WroteFile = *Success;
        if (WroteFile) {
          fmt::print("Saving crash in {}\n", OutputPath.string());
        }
      }
    }
```
- Now in terms of snapshotting, you can really snapshot wherever you want. The idea is that you want to pick a place where it makes your life easier: it allocates memory for you (as you can't extend existing allocation once you snapshot'ed, etc), and exercise all the code you want to target; from user to kernel, kernel to user, only user or only kernel. 

- Now, in this case you are reusing an existing [fuzzer module](https://github.com/0vercl0k/wtf/blob/841ba28236690ad8b08f4e46886ee18036eecba8/src/wtf/fuzzer_hevd.cc) which has assumptions baked on how the snapshotting happened. For this module, I used this [hevd_client.cc](https://github.com/0vercl0k/wtf/blob/841ba28236690ad8b08f4e46886ee18036eecba8/src/hevd_client/hevd_client.cc) with the `BREAK` environment variable to control the break. If you load the `state.dmp` in windbg you can exactly see where I generated the snapshot (I actually took it in usermode):
```
hevd_client!main+0xae:
00007ff6`f5bb111e ff15dc1e0100    call    qword ptr [hevd_client!_imp_DeviceIoControl (00007ff6`f5bc3000)] ds:002b:00007ff6`f5bc3000={KERNEL32!DeviceIoControlImplementation (00007ff8`3e2e6360)}

kd> lsa .
    17:         __debugbreak();
    18:     }
    19: 
    20:     DWORD Returned = 0;
>   21:     DeviceIoControl(
    22:         H,
    23:         0xdeadbeef,
    24:         Buffer.data(),
    25:         Buffer.size(),
    26:         Buffer.data(),
```

Does this help?

Cheers

**Comment by Flerov** [comment]
1.
Thanks a lot for your thorough reply.
It helped me a lot.
I tried a lot but never managed to step to this part of the code "call    qword ptr [hevd_client!_imp_DeviceIoControl[...]" and be able to take a dump.
When I was using ntsd util to spawn the process I was seeing the exact same call but to take the dump I needed to switch context back from target application to kernel thus my context changed and the registers were filled from the DebugBreak instruction. Using .process hevd_client didnt work in this way. It was giving me a hard time the last few days (too unexperienced). So the dump that caused my question was taken at that point.

I finally tried it again by setting the env var "BREAK" but I'm no longer able to see the exact same call to _imp_DeviceIoControl. Instead I only see a mov instruction at that point so I was just walking into and landed inside DeviceIoControlImplementation and took the dump right at the beginning and everything works as expected the crashes and outputs are being saved.

2. I was messing with your HEVD example and loaded the provided tenet.trace into IDA somehow the ASLR was not found so I rebased the image "myself" but my trace looks way different then yours I cannot reproduce the same path backwards you took in the short video in your readme. So I was wondering (because of my constant ASLR fail, when loading a trace) if you took any other trace or the provided tenet.trace from the traces folder?

Thanks again for the amount of help

**Comment by 0vercl0k** [comment]
Oh yes, the break will make you break at the artificial `int3`; you can rewrite it dynamically with `eb . 90` and step over it until your desired spot; I took the dump on the `call [&DeviceIoControl]` 🙂

Can I help you with anything else?

Cheers

**Comment by Flerov** [comment]
No thank you I will close the issue
