### ISSUE TITLE
Own Fuzzer build fails: Did you forget to include "#include "path/to/wtf/src/build/CMakeFiles/wtf.dir/RelWithDebInfo/cmake_pch.hxx"

### ISSUE THREAD

**Issue by Flerov** [0vercl0k/wtf#154]
Hey again.
So I'm currently trying to fuzz some network packets in kernel and made the kernel hook and user application as similar as I could to your hevd example.
I thought I could just reuse the  hevd_fuzzer since my dump is also right at the call to DeviceIoControl. In WinDbg it looks like this:
00007fff`7c328e8c ff156ed20000    call    qword ptr [WinDivert!_imp_DeviceIoControl (00007fff`7c336100)] ds:002b:00007fff`7c336100={KERNEL32!DeviceIoControlImplementation (00007fff`8ee75b70)}
but it seems like it doesnt work like this. Though I can start both server and fuzzer I dont get any crashes and my fuzzer windows get spammed with "nt!SwapContext" prints.

So I was trying to add my own fuzzer "passthru_fuzzer.cc" to the wtf-solution I copied the code from hevd_fuzzer.cc and changed the namespace. Compiling the project results in the error:
 Did you forget to include "#include "path/to/wtf/src/build/CMakeFiles/wtf.dir/RelWithDebInfo/cmake_pch.hxx"
 
 Any help again much appreciated

**Comment by Flerov** [comment]
I dont see why this error occurs in first place or how I could fix this since the precompiled headers are all included in the projects-settings... compiling without my passthru_fuzzer.cc also never resulted in that error

**Comment by 0vercl0k** [comment]
When you add a new file, just re-run `cmake ..` from the directory where
the Visual Studio solution is - it should pick up the new files and updates
the solution.

Let me know if it doesn't work.

Cheers

**Comment by 0vercl0k** [comment]
Could you please run what I suggested above?

Cheers

**Comment by Flerov** [comment]
Yes. Thank you alot.
Youre stunning with your fast replies :D

**Comment by 0vercl0k** [comment]
Awesome! Thank YOU for playing with wtf :)

Cheers

**Comment by 0vercl0k** [comment]
Closing as it seems your issue is fixed.

Cheers
