### ISSUE TITLE
Diagnosing differences between bochs backend and Hyper-V backend

### ISSUE THREAD

**Issue by warwick-davis** [0vercl0k/wtf#160]
Is there any defined protocol or recommended method to figure out why a testcase may be crashing on Hyper-V but not on Bochs (nor on real CPU)?

I wanted to try and get a trace to see where they diverge but it is only supported on Bochs unfortunately. Any help would be appreciated.

**Comment by 0vercl0k** [comment]
One of the way I've done that before is by using the code coverage trace
(you get an address per basic block) and you can start comparing this with
a full RIP bochs trace. It's tedious but it should give you an idea where
execution diverges and why.

Cheers

**Comment by warwick-davis** [comment]
Unfortunately I had to make a new dump regardless and I ran into bigger issues, but useful for the future, thanks!
