### ISSUE TITLE
translation of GVA 0xe failed

### ISSUE THREAD

**Issue by areuu** [0vercl0k/wtf#17]
Hi, I'm following the README to dump, but when I want to fuzz, it throw 

H:\fuzz_example\hevd>H:\fuzz\wtf\src\build\wtf.exe fuzz --backend=bochscpu --name hevd --max_len 1028 --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
Dialing to tcp://localhost:31337/..
Translation of GVA 0xe failed

**Comment by areuu** [comment]
Here is dump file https://mega.nz/file/Zps2yJDT#RkyfqBDZamwePScQYlHLFGJnEOt6twdHVR7zCxI61bk

**Comment by areuu** [comment]
I don't modify the fuzzer_hevd.cc file.

**Comment by 0vercl0k** [comment]
Right so if you look at those lines of code: https://github.com/0vercl0k/wtf/blob/main/src/wtf/fuzzer_hevd.cc#L44-L49:

```C++
  const Gva_t IoctlBufferPtr = Gva_t(g_Backend->R8());
  if (!g_Backend->VirtWriteDirty(IoctlBufferPtr, IoctlBuffer,
                                 IoctlBufferSize)) {
    DebugPrint("VirtWriteDirty failed\n");
    return false;
  }
```

It reads the `@r8` register and will do a virtual memory write to the memory it points to, but your snapshot has `@r8` set to `0xe`:

```
kd> r @r8
r8=000000000000000e
```

So it works as expected - feel free to re-open if it doesn't make sense.

Cheers
