### ISSUE TITLE
During bochscpu simulation, data from the heap is not fetched correctly.

### ISSUE THREAD

**Issue by g3un** [0vercl0k/wtf#194]
I don't know if it's a problem with the bochscpu code or the backend code, but there was a problem where the pointer in the heap could not be retrieved properly.

When opening a dump created with snapshot with windbg:

```plaintext
kd> dq rcx
00000204`b6e0b060  00007ff8`20a98f80 00007ff8`20a98f80
00000204`b6e0b070  00007ff8`20add720 00007ff8`20add720
00000204`b6e0b080  00d9f791`00000000 00000204`b6e0c5fe
00000204`b6e0b090  00000000`0000000e 00000204`b6e0bef0
00000204`b6e0b0a0  0000073e`00001000 00000204`b6e0cef0
00000204`b6e0b0b0  00000000`00001000 00000000`00000000
00000204`b6e0b0c0  00000000`00000000 000e0001`00000001
00000204`b6e0b0d0  00000204`b6e0befe 00000000`00000000
```

However, the first time rcx+48(`0x00000204b6e0b0a8`) is accessed in the Tenet trace is as follows:

![image](https://github.com/0vercl0k/wtf/assets/92908037/29fbf895-06c8-4e64-b49f-fe0900af5a73)

The pc at that point is `mov r8, [rbx+10h]` and rbx is `0x204B6E0B098`.

Do you know anything about cases where the lower 4 bytes are lost as shown above?

**Comment by g3un** [comment]
Ah, I used the g_backend method incorrectly. sorry.

**Comment by 0vercl0k** [comment]
No worries :)

Cheers
