### ISSUE TITLE
broken emulation on specific circumstance

### ISSUE THREAD

**Issue by y0ny0ns0n** [0vercl0k/wtf#21]
Backend : bochscpu
trace creation : bochscpu
Dump VM environment: Hyper-V Gen1 VM, 1 CPU, 4GB RAM

---

During when I tried to fuzzing some windows kernel component, I encounter some page fault.

![Animation](https://user-images.githubusercontent.com/47174372/131530917-05b8ef60-fa73-499c-acdb-5d002003c5bf.gif)
( `0xFFFFF8056CC05000` is `nt!KiPageFault` )

`nt!MmAccessFault`'s return value was 0x110( =`STATUS_PAGE_FAULT_TRANSITION` ). I don't know why transition fault was happened at there but I didn't care much about that because it executes normally after that transition fault.

But the real problem happened when transition fault occured on conditional jump instruction.
![Animation2](https://user-images.githubusercontent.com/47174372/131533487-60021efc-c6c0-4fdd-8506-becdd2efc50c.gif)

Transition fault occured on `FFFFB1929ADE6483` but saved return address is `FFFFB1929AE964E7`. 
It is a next insturction after `jz`, so `FFFFB1929AE964E7` will be executed after execution context restored from interrupt...and it was executed exactly as below.

![Animation3](https://user-images.githubusercontent.com/47174372/131535295-d37f8765-3c9f-4e6e-9a6a-f652dbfaac0b.gif)

As you can see, emulator is broken and it execute as 2-byte aligned.
```
0xfffff8056cc05638 <- end of nt!KiPageFault( iretq )
0xffffb1929ae964e7 <- instruction of fuzzed kernel component...and 2 byte aligned execution for unknown reason
0xffffb1929ae964e9
0xffffb1929ae964eb
0xffffb1929ae964ed
0xffffb1929ae964ef
0xffffb1929ae964f1
0xffffb1929ae964f3
0xffffb1929ae964f5
0xffffb1929ae964f7
0xffffb1929ae964f9
0xffffb1929ae964fb
0xffffb1929ae964fd
0xffffb1929ae964ff
```

I tried to catch that circumstance using `SetBreakpoint` on `nt!KiPageFault` but I couldn't find any method to get previous instruction address on breakpoint handler, so I will be very pleased if you let me know any good method for that.

**Comment by 0vercl0k** [comment]
Thanks for the detailed report - I'll take a look at this this week-end :).
I suppose you cannot share the dump / regs.json file? It'd probably make
debugging much easier. But if you can't share it I'll do my best without it!

Cheers

**Comment by y0ny0ns0n** [comment]
If you give me your e-mail, I will send those files which need to reproduce.

**Comment by 0vercl0k** [comment]
Actually, we might not need it - @yrp604 and I quickly looked at it
yesterday night; it sounds like you might be executing paged out driver
code which wtf would zero-fills the page. This means you would end up
executing a bunch of 'add    BYTE PTR [rax],al' which are two bytes long.

Can you try to `VirtReadMem(0xffffb1929ae964e9)` at the end of the
execution / or before executing the `iretq` to verify the above?

Cheers

**Comment by y0ny0ns0n** [comment]
you and @yrp604 found answer!

**Comment by y0ny0ns0n** [comment]
You and @yrp604 found answer!

I add following code on `Init()`:
```c
    // FFFFF8056CC05638 = nt!KiPageFault+0x638 == iretq
    if(!g_Backend->SetBreakpoint(Gva_t(0xFFFFF8056CC05638), [](Backend_t *Backend) {
        uint64_t ret_addr = g_Backend->VirtRead8(Gva_t(Backend->Rsp()));
        uint64_t value = g_Backend->VirtRead8(Gva_t(ret_addr));

        DebugPrint("iretq return addr = {:#x}\n", ret_addr);
        DebugPrint("value = {:#x}\n", value);
    })) {
        return false;
    }
```

and the result is...
![image](https://user-images.githubusercontent.com/47174372/131694242-b4737de4-3085-44f4-85fb-613981f7c003.png)

Is there method to mapping whole driver code image?

**Comment by y0ny0ns0n** [comment]
BTW, my target driver was win32kbase.sys -_-

**Comment by 0vercl0k** [comment]
OK cool, @yrp604 is the man :).

All right so I have never run into this case yet even though I was aware this was possible to happen. I think the first thing to verify is that the page is really paged-out on disk and it's not because of something funky like the session space.

Then maybe you can try to run your VM without a pagefile (I've done it a few times and works fine)?

Cheers

**Comment by y0ny0ns0n** [comment]
Ok. I make new snapshots after [disable pagefile and reboot](https://www.tomshardware.com/reviews/ssd-performance-tweak,2911-4.html). active kernel dump show same issue above but full dump works fines as below:

![image](https://user-images.githubusercontent.com/47174372/131708784-568d7e3b-e0ee-405f-8ec3-4c75320d05c8.png)

**Comment by 0vercl0k** [comment]
Awesome to hear - hope you find a lot of bugs :)

Cheers
