### ISSUE TITLE
bochscpu

### ISSUE THREAD

**Issue by djn3m0** [0vercl0k/wtf#43]
Hi,

I read part of the code and got interested to play a bit with bochscpu, I went to https://github.com/yrp604/bochscpu-build but that seem to be different than what you used in this project!

Like some functions like `bochscpu_cpu_new()` and many others that you used in this repository doesn't exist there! 
```
    bochscpu_cpu_t Cpu_ = nullptr;
    Cpu_ = bochscpu_cpu_new(0);
```

Can you please give me some clue on where I can start using bochscpu and what is the different between what is used in this project and the one in yrp604/bochscpu-build?

Thanks,
Nemo

**Comment by 0vercl0k** [comment]
Hello,

Yeah so there are multiple projects associated with bochscpu:
- https://github.com/yrp604/bochscpu (checkout the `src` directory),
- https://github.com/yrp604/bochscpu-ffi for the FFI,
- https://github.com/yrp604/bochscpu-build for building it all!

Tagging the author as well, cc @yrp604.

Cheers

**Comment by djn3m0** [comment]
I can see those function names under yrp604/bochscpu-ffi but they are in rust. Under yrp604/bochscpu-build I don't see any header that expose those functions!

Appreciate the quick response

**Comment by 0vercl0k** [comment]
The headers are generated by the ffi project I believe :)

Cheers

**Comment by yrp604** [comment]
There are 4 repos associated with bochscpu right now:
- bochscpu, this is the main rust library that wraps the bochs cpu code and exposes a rust api to library consumers
- bench, this is an easy test to make sure your install of bochscpu works as well as an example of how instantiate an x64 cpu from scratch
- ffi, this exposes a C ffi layer to bochscpu. This layer provides an autogenerated header from the rust code using cbindgen, as well as a C abi static and dynamic library.
- build, this is mostly a repo that uses CI to provide pre-built bochs executables as building the cpu core is kinda a pain. Unless you need to change the bochs cpu core, you should only need to download the pre-built artifacts from here.

So, putting this all together, to use bochscpu from C:
1. Install rust nightly via rustup
2. Clone bochscpu and bochscpu-bench, and download the artifacts from bochscpu-build release
3. Install the artifacts from build into the bochscpu directory, as described in the bochscpu readme
4. Run bochscpu-bench -- if this works you've installed everything correctly. At this point you can delete the bench project if you want.
5. Clone the ffi bindings
6. Build the ffi bindings (`cargo build --release`). You should now have a bochscpu library and header in `target/release`

Note that the directory structure does matter slightly here for building. `bochscpu`, `bochscpu-bench` and `bochscpu-ffi` should all live in the same directory. Once you've got the headers and the library out of ffi they should be standalone.

**Comment by 0vercl0k** [comment]
Feel free to reopen if you have other questions @djn3m0!

Cheers

**Comment by djn3m0** [comment]
Hi, 

@yrp604 Thanks for nice step by step explanation.

I ran into the following error while doing what you explained,

This is how the directory structure look like,

```
>ls
bochscpu  bochscpu-bench  bochscpu-ffi
```

And after running `bochscpu-bench`,

```
creating a mapping from gva 0x41410000 to gpa 0x81810000 for the text...
creating a mapping from gva 0x12345000 to gpa 0x67890000 for the stack...
mapping gpa 0x81810000 to hva 0x1fb55eb0000...
mapping gpa 0x12345000 to hva 0x1fb55ec0000...
page table serialized, base @ 0x0
mapping page table gpa 0x0 to hva 0x1fb55ed0000...
mapping page table gpa 0x1000 to hva 0x1fb55ee0000...
mapping page table gpa 0x2000 to hva 0x1fb55ef0000...
mapping page table gpa 0x3000 to hva 0x1fb55f00000...
mapping page table gpa 0x4000 to hva 0x1fb55f10000...
mapping page table gpa 0x5000 to hva 0x1fb55f20000...
setting up cpu registers...
rax=0000000000000000 rbx=0000000000000000 rcx=0000000000000000
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
rip=0000000041410000 rsp=0000000012345800 rbp=0000000000000000
 r8=0000000000000000  r9=0000000000000000 r10=0000000000000000
r11=0000000000000000 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
writing 34 bytes of fib code to gva 0x41410000...
setting up emulation hooks...
done, starting emulation...
result in rax is afe41bcaba69f23b, 16777215 loops
emulated 201326584 ins with 50331645 mem reads and 50331648 mem writes in 4.1680126s, 50.33m ips
```

Now the problem is when I tried to build `bochscpu-ffi`,

```
\bochscpu-ffi>cargo build --release
   Compiling bochscpu-ffi v0.1.0 (C:\Users\nemo\Desktop\bochs+\bochscpu-ffi)
error[E0425]: cannot find function `missing_page` in this scope
  --> src\mem.rs:41:5
   |
41 |     missing_page(move |gpa| handler(gpa))
   |     ^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `bochscpu-ffi` due to previous error
```

Thanks to both of you :)

**Comment by 0vercl0k** [comment]
I am not sure if it is of help but I've checked in the scripts I used to
build it myself:
https://github.com/0vercl0k/wtf/blob/main/src/libs/build-bochscpu.bat /
https://github.com/0vercl0k/wtf/blob/main/src/libs/build-bochscpu.sh.

Cheers

**Comment by yrp604** [comment]
Okay, this is due to me updating bxcpu but. It the bindings. I can probably have this fixed by tonight.

**Comment by djn3m0** [comment]
Awesome thanks.

**Comment by yrp604** [comment]
ffi repo is updated and should build for you.

Note that the `missing_page` callback has been moved into the hook structure. Same functionality, just invoked differently.

**Comment by djn3m0** [comment]
I confirm that I managed to build this and use the library in a C project.

Thanks again.

**Comment by 0vercl0k** [comment]
wooot, awesome!
