### ISSUE TITLE
using 32bit registers

### ISSUE THREAD

**Issue by fish3rman** [0vercl0k/wtf#46]
When fuzzing wow64 application, can I use 32-bit register (eax, ebx, esp...) values in InsertTestcase function? Only the 64-bit register was declared in backend.h. Should I use it in such a way that I get the x64 register and get only the lower 4 bytes?

**Comment by 0vercl0k** [comment]
I think you should use the x64 register and use the lower 4 bytes only yeah
:)

Cheers
