### ISSUE TITLE
how to fix kvm_backend build error

### ISSUE THREAD

**Issue by fr0zenrain** [0vercl0k/wtf#47]
it has a build error on ubuntu 18.04,the output as follows.and i install the qemu-kvm by apt

kvm_backend.cc:255:7: error: use of undeclared identifier 'KVM_SYNC_X86_REGS'
      KVM_SYNC_X86_REGS | KVM_SYNC_X86_SREGS | KVM_SYNC_X86_EVENTS;
      ^
kvm_backend.cc:872:16: error: no member named 'sregs' in 'kvm_sync_regs'
  Run_->s.regs.sregs.cr8 = CpuState.Cr8;

how do fix it? thanks.

**Comment by 0vercl0k** [comment]
What version of Ubuntu this is?

Cheers

**Comment by 0vercl0k** [comment]
Sorry it is included in the email, my bad 🤦🏽I'll check it out.

**Comment by 0vercl0k** [comment]
What's your kernel version?

**Comment by fr0zenrain** [comment]
my kernel is 5.11.4.

**Comment by 0vercl0k** [comment]
Hmmm weird, I can see it defined: [kvm.h](https://elixir.bootlin.com/linux/v5.11.4/source/arch/x86/include/uapi/asm/kvm.h#L381) / [KVM_SYNC_X86_REGS](https://elixir.bootlin.com/linux/v5.11.4/A/ident/KVM_SYNC_X86_REGS)

**Comment by 0vercl0k** [comment]
Did you find the issue? I'd be interested to hear about it if you did :)

Cheers

**Comment by fr0zenrain** [comment]
my system include path "/usr/include/x86_64-linux-gnu" and "/usr/include".they all have kvm.h,but it's different from the kernel source,i don't know the reason why I use apt install and make headers_install did not update these files.At last,I copy two files by manual,finally resolved.thanks!

**Comment by 0vercl0k** [comment]
Awesome - thanks for sharing!

Cheers

Le sam. 11 déc. 2021 à 16:56, fr0zenrain ***@***.***> a
écrit :
