### ISSUE TITLE
The issue about hyper-v in intel cpu

### ISSUE THREAD

**Issue by willinin** [0vercl0k/wtf#63]
I test the program by the hyper-v backend on intel cpu  win10 and win11. And get errors:

Initializing the debugger instance.. (this takes a bit of time)
Setting Efer failed
Failed to LoadState
Backend failed initialization.

I found the  WHvX64RegisterEfer set by WHvSetVirtualProcessorRegisters function always failed on intel cpu.

**Comment by willinin** [comment]
And amd cpu is OK!   So, what is WHvX64RegisterEfer ?

**Comment by 0vercl0k** [comment]
Hello,

That is interesting - I have never encountered an issue with Efer (
https://wiki.osdev.org/CPU_Registers_x86-64#IA32_EFER).

How did you acquire the dump for your target? On an Hyper-V VM or not?

Also if you are able to share the state folder I can take a look at this -
if not no worries.

Cheers

**Comment by willinin** [comment]
Sorry. I'm stupid.  I take a  vm-snapshot on amd machine then run on intel machine.   Thanks.

**Comment by 0vercl0k** [comment]
Ha yeah that's probably the issue then :)

Cheers
