### ISSUE TITLE
enhancement suggestion for network protocol fuzzing

### ISSUE THREAD

**Issue by y0ny0ns0n** [0vercl0k/wtf#64]
Hi.

During fuzzing campaign, I tried to fuzz some network component with wtf and I felt a necessary for persistence option.

Some network protocols requires multi inputs for initialize and processing instead one big testcase like file format. 
I tried to split single testcase and create custom format for fuzzing but instead of that, I think it will be better if I can receive testcase from server on Breakpoint handler even multiple times in single execution.

I want to contribute for this part but I dunno where to look at. Do you have recommend for where should I look at or any other ideas for network protocol fuzzing?

Sincerely.

**Comment by 0vercl0k** [comment]
Hello,

Apologies for the delayed answer, for whatever reason I forgot to answer this. Sorry can you describe a bit more how this would work? I am not 100% sure I understand what you're looking for 😅

Cheers

**Comment by y0ny0ns0n** [comment]
Hi,

I want to fuzz some targets like this:
https://www.cyberark.com/resources/threat-research-blog/fuzzing-rdp-holding-the-stick-at-both-ends 

Those kind of target requires multiple rpc or packet send like first send create memory object with user-provided type and second send processing data based on object created on first call. To efficiently fuzz a target like this, fuzzer needs a ability to send multiple testcases to the target on single runtime.

I could have been guessed wrong but I think wtf needs a testcase receiver on breakpoint handler to support this kind of fuzz type( persistence fuzzing maybe? ).

Sincerely.

**Comment by 0vercl0k** [comment]
Right I understand your need and it makes sense. This is something you could hack with `wtf` where when you receive the testcase you store it in global state - you can then insert part of the testcase whenever you want during execution: for example every time a specific breakpoint get hit.

Are you suggesting to improve that, or were you asking if this is possible?

Cheers

**Comment by 0vercl0k** [comment]
If you need any help please let me know - happy to contribute / test :)

Cheers!

Le mer. 12 janv. 2022 à 18:03, y0ny0ns0n ***@***.***> a
écrit :
