### ISSUE TITLE
unused --max_len option on fuzz mode

### ISSUE THREAD

**Issue by y0ny0ns0n** [0vercl0k/wtf#65]
I couldn't found any usage of `TestcaseBufferMaxSize` on fuzz mode( which defined in [here](https://github.com/0vercl0k/wtf/blob/2d4eeae/src/wtf/wtf.cc#L299-L303) ).

Is it exists for reasons?

**Comment by 0vercl0k** [comment]
Let me have a look - at one point it was needed to allocate the buffer where the testcase were received / mutated..
