### ISSUE TITLE
Crash in wtf!Client_t::SendResult+0x1b7 [C:\wtf\src\wtf\client.cc @ 200]

### ISSUE THREAD

**Issue by vportal** [0vercl0k/wtf#77]
Hello,

I am getting the crash below when trying to fuzz a kernel driver:

```
EXCEPTION_CODE_STR:  80000003

EXCEPTION_PARAMETER1:  0000000000000000

STACK_TEXT:  
000000bd`f98fd2b0 00007ffc`94177ee2     : 00000209`7e3a0000 00007ffc`941d77f0 00000000`00000003 00000209`7e3a0000 : ntdll!RtlReportCriticalFailure+0x56
000000bd`f98fd3a0 00007ffc`941781ca     : 00000000`00000003 00000000`00000000 00000209`7e3a0000 00000000`0000021c : ntdll!RtlpHeapHandleError+0x12
000000bd`f98fd3d0 00007ffc`9417de51     : 00000209`7e3a0000 00000209`7e3a0000 00000209`3ff7a010 00000000`00000000 : ntdll!RtlpHpHeapHandleError+0x7a
000000bd`f98fd400 00007ffc`94117142     : 00000209`7e3a0000 00000209`7e3a0000 00000000`00000000 00000209`7e3a0000 : ntdll!RtlpLogHeapFailure+0x45
000000bd`f98fd430 00007ffc`940947b1     : 00000209`7e3cc838 00000209`7e3a0000 000000bd`f98fd631 00000000`00000000 : ntdll!RtlpFreeHeapInternal+0x81a32
000000bd`f98fd4f0 00007ffc`9197f05b     : 00000209`3feefd80 00000000`00000001 00000000`00000000 00000000`00000000 : ntdll!RtlFreeHeap+0x51
000000bd`f98fd530 00007ff6`6f2070a8     : 00000000`00000001 00000000`00000000 00008e8e`029f65d5 000000bd`f98fef50 : ucrtbase!_free_base+0x1b
000000bd`f98fd560 00007ff6`6f205167     : 00000209`3feefd80 000000bd`f98fd5b8 00000000`000000af 000000bd`f98fd5b8 : wtf!std::_Ref_count_resource<char *,void (__cdecl*)(char *)>::`scalar deleting destructor'+0x18
000000bd`f98fd590 00007ff6`6f20546b     : 000000bd`f98fd7a0 000000bd`f98fd719 000000bd`f98fef50 00000209`7e3aaab8 : wtf!Client_t::SendResult+0x1b7 [C:\wtf\src\wtf\client.cc @ 200] 
000000bd`f98fd690 00007ff6`6f22e95c     : 000000bd`f98fd7a0 00000000`00000000 000000bd`f98fef50 000000bd`f98fef50 : wtf!Client_t::Run+0x21b [C:\wtf\src\wtf\client.cc @ 251] 
000000bd`f98fd780 00007ff6`6f255258     : 00007ff6`70da05d8 00007ff6`70da05d8 00007ff6`70da05d8 00000209`7e3aaab8 : wtf!FuzzSubcommand+0x2c [C:\wtf\src\wtf\subcommands.cc @ 96] 
000000bd`f98fd7f0 00007ff6`6f425a5c     : 00000000`00000000 00000000`00000000 00000209`7e3a2d30 00000000`00000000 : wtf!main+0x1d38 [C:\wtf\src\wtf\wtf.cc @ 426] 
000000bd`f98ffa20 00007ffc`92ee7034     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wtf!__scrt_common_main_seh+0x10c [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
000000bd`f98ffa60 00007ffc`940c2651     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : KERNEL32!BaseThreadInitThunk+0x14
000000bd`f98ffa90 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x21


SYMBOL_NAME:  ntdll!RtlReportCriticalFailure+56

MODULE_NAME: ntdll

IMAGE_NAME:  ntdll.dll

IMAGE_VERSION:  10.0.19041.1466

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  56

FAILURE_BUCKET_ID:  0x0_VRF_ntdll!RtlReportCriticalFailure

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {73ce741a-e3b8-1889-e74b-f6e20476df31}

Followup:     MachineOwner
```

I think there is something wrong in my harness because other targets are working properly but i don't see the root cause with the dump information. I just trying to fuzz a specific function in the driver that parse network messages. i got the dump when the BP of the frist function instruction is reached and stop when the RETN of the same function is reached. 

Best regards,
Víctor

**Comment by 0vercl0k** [comment]
Would you be able to share the fuzzing module by any chance? A redacted
version should be enough to help me understand where the issue might be :)

Cheers

**Comment by vportal** [comment]
Yes, no problem:

`#include "backend.h"
#include "targets.h"
#include <fmt/format.h>

namespace fs = std::filesystem;


namespace NetworkDriver {


uint64_t g_Rsp, g_Rip, g_Rax, g_Rbx, g_Rcx, g_Rdx, g_Rsi, g_Rdi,
         g_R8, g_R9, g_R10, g_R11, g_R12, g_R13, g_R14, g_R15;

void Save64bitRegs() {
  g_Rsp = g_Backend->Rsp();
  g_Rip = g_Backend->Rip();
  g_Rax = g_Backend->Rax();
  g_Rbx = g_Backend->Rbx();
  g_Rcx = g_Backend->Rcx();
  g_Rdx = g_Backend->Rdx();
  g_Rsi = g_Backend->Rsi();
  g_Rdi = g_Backend->Rdi();
  g_R8  = g_Backend->R8();
  g_R9  = g_Backend->R9();
  g_R10 = g_Backend->R10();
  g_R11 = g_Backend->R11();
  g_R12 = g_Backend->R12();
  g_R13 = g_Backend->R13();
  g_R14 = g_Backend->R14();
  g_R15 = g_Backend->R15();
}

void Restore64bitRegs() {
  g_Backend->Rsp(g_Rsp);
  g_Backend->Rip(g_Rip);
  g_Backend->Rax(g_Rax);
  g_Backend->Rbx(g_Rbx);
  g_Backend->Rcx(g_Rcx);
  g_Backend->Rdx(g_Rdx);
  g_Backend->Rsi(g_Rsi);
  g_Backend->Rdi(g_Rdi);
  g_Backend->R8(g_R8);
  g_Backend->R9(g_R9);
  g_Backend->R10(g_R10);
  g_Backend->R11(g_R11);
  g_Backend->R12(g_R12);
  g_Backend->R13(g_R13);
  g_Backend->R14(g_R14);
  g_Backend->R15(g_R15);
}

constexpr bool LoggingOn = false;

template <typename... Args_t>
void DebugPrint(const char *Format, const Args_t &...args) {
  if constexpr (LoggingOn) {
    fmt::print("NetworkDriver: ");
    fmt::print(Format, args...);
  }
}

bool InsertTestcase(const uint8_t *Buffer, const size_t BufferSize) {
  if (BufferSize < sizeof(uint32_t)) {
    return true;
  }

  
  if (BufferSize > 512 && BufferSize < 48) {
    return true;
  }
  
  const uint32_t ID = *(uint32_t *)Buffer; //extract the packet ID 
  
  const size_t PacketBufferSize = BufferSize - sizeof(uint32_t);
  const uint8_t *PacketBuffer = Buffer + sizeof(uint32_t);
  
  /*
  __int64 __fastcall ParseMessage(__int64 a1, unsigned int a2, unsigned int **a3, char a4)
  
*/

  //R8=ffff850f46e20e50 Poi(r8)= ffff850f4b7daf80  
  
  uint64_t poi_r8; //poi(r8) - read the pointer stored in r8
  if(!g_Backend->VirtReadStruct(Gva_t(g_Backend->R8()), &poi_r8)) {
    DebugPrint("Failed to read RdnisBuffer pointer in testcase injection!");
    return false;
  }
  

  const uint8_t *PktBuffer = (uint8_t*)PacketBuffer;
  *(DWORD*)(PktBuffer + 16) = PacketBufferSize-0x14; 
  *(DWORD*)(PktBuffer + 32) = ID;
  *(DWORD*)(PktBuffer + 36) = 0x0;

  if (!g_Backend->VirtWriteDirty(Gva_t(poi_r8), PktBuffer,
                                 BufferSize)) {
	DebugPrint("VirtWriteDirty failed\n"); //write the buffer in the pointer previous stored in r8 --  unsigned int **a3
    return false;
  }

  return true;
}
bool Init(const Options_t &Opts, const CpuState_t &) {
  //
  // Stop the test-case in the RETN instruction of [ParseMessage]
  //
  const Gva_t Rip = Gva_t(g_Backend->Rip()); //00000001C0043940
  const Gva_t AfterCall = Rip + Gva_t(0x44C); //0x00000001C0043D8C
  
  Save64bitRegs();
  
  if (!g_Backend->SetBreakpoint(AfterCall, [](Backend_t *Backend) {
	    Restore64bitRegs();
        DebugPrint("Reached ParseMessage function end\n");
        Backend->Stop(Ok_t());
      })) {
    DebugPrint("Failed to SetBreakpoint AfterCall\n");
    return false;
  }
  

  //
  // NOP the calls to DbgPrintEx.
  //

  if (!g_Backend->SetBreakpoint("nt!DbgPrintEx", [](Backend_t *Backend) {
        const Gva_t FormatPtr = Backend->GetArgGva(2);
        const std::string &Format = Backend->VirtReadString(FormatPtr);
        DebugPrint("DbgPrintEx: {}", Format);
        Backend->SimulateReturnFromFunction(0);
      })) {
    DebugPrint("Failed to SetBreakpoint DbgPrintEx\n");
    return false;
  }

  //
  // Make ExGenRandom deterministic.
  //
  // kd> ub fffff805`3b8287c4 l1
  // nt!ExGenRandom+0xe0:
  // fffff805`3b8287c0 480fc7f2        rdrand  rdx
  const Gva_t ExGenRandom = Gva_t(g_Dbg.GetSymbol("nt!ExGenRandom") + 0xe4);
  if (!g_Backend->SetBreakpoint(ExGenRandom, [](Backend_t *Backend) {
        DebugPrint("Hit ExGenRandom!\n");
        Backend->Rdx(Backend->Rdrand());
      })) {
    return false;
  }

  //
  // Catch bugchecks.
  //

  if (!g_Backend->SetBreakpoint("nt!KeBugCheck2", [](Backend_t *Backend) {
        const uint64_t B0 = g_Backend->GetArg(1);
        const uint64_t B1 = g_Backend->GetArg(2);
        const uint64_t B2 = g_Backend->GetArg(3);
        const uint64_t B3 = g_Backend->GetArg(4);
        const uint64_t B4 = g_Backend->GetArg(5);
        const std::string Filename = fmt::format(
            "crash-{:#x}-{:#x}-{:#x}-{:#x}-{:#x}", B0, B1, B2, B3, B4);
        DebugPrint("KeBugCheck2: {}\n", Filename);
        Backend->Stop(Crash_t(Filename));
      })) {
    return false;
  }

  //
  // Catch context-switches.
  //

  if (!g_Backend->SetBreakpoint("nt!SwapContext", [](Backend_t *Backend) {
        DebugPrint("nt!SwapContext\n");
        Backend->Stop(Cr3Change_t());
      })) {
    return false;
  }

  return true;
}

bool Restore() { return true; }

//
// Register the target.
//

Target_t NetworkDriver("networkDriver", Init, InsertTestcase, Restore);

} // namespace NetworkDriver`

Thanks!

**Comment by 0vercl0k** [comment]
Okay, so I think there might be an issue here:
```c++
  if (!g_Backend->VirtWriteDirty(Gva_t(poi_r8), PktBuffer,
                                 BufferSize)) {
```

Passing `BufferSize` means that you are reading out of bounds of the `PktBuffer` no? This wouldn't lead to the heap corruption you are seeing though.

By looking at your crash, it looks like you've overflowed the testcase buffer so it kind of lead us to those lines but they look fine to me:
```c++
  const uint8_t *PktBuffer = (uint8_t*)PacketBuffer;
  *(DWORD*)(PktBuffer + 16) = PacketBufferSize-0x14; 
  *(DWORD*)(PktBuffer + 32) = ID;
  *(DWORD*)(PktBuffer + 36) = 0x0;
```

Do you mind turning on page heap on `wtf.exe` and seeing if you can get a crash closer from when you're causing the corruption?

Cheers

**Comment by vportal** [comment]
Stupid mistake 😅

Now is working properly! Thank you both!

Best regards

**Comment by 0vercl0k** [comment]
Cheers! 🍻
