### ISSUE TITLE
Page faults on usermode target?

### ISSUE THREAD

**Issue by expend20** [0vercl0k/wtf#82]
Hello there and thank you for awesome project to play with!

I'm trying to fuzz usermode program using bochscpu backend and only coverage I'm getting (in aggregate.cov) is related to page faults i.e. nt!KiPageFault, nt!MmAccessFault, nt!MiUserFault, ...

My target is fairly simple, memory dump is taken on this first instruction:
```
0033:00007ff8`5aaa2f20 83fa08         cmp     edx, 8
0033:00007ff8`5aaa2f23 7233           jb      00007ff8`5aaa2f58
0033:00007ff8`5aaa2f25 803931         cmp     byte ptr [rcx], 31h
0033:00007ff8`5aaa2f28 752e           jne     00007ff8`5aaa2f58
0033:00007ff8`5aaa2f2a 80790133       cmp     byte ptr [rcx+1], 33h
0033:00007ff8`5aaa2f2e 7528           jne     00007ff8`5aaa2f58
0033:00007ff8`5aaa2f30 80790233       cmp     byte ptr [rcx+2], 33h
0033:00007ff8`5aaa2f34 7522           jne     00007ff8`5aaa2f58
0033:00007ff8`5aaa2f36 80790337       cmp     byte ptr [rcx+3], 37h
0033:00007ff8`5aaa2f3a 751c           jne     00007ff8`5aaa2f58
0033:00007ff8`5aaa2f3c 80790431       cmp     byte ptr [rcx+4], 31h
0033:00007ff8`5aaa2f40 7516           jne     00007ff8`5aaa2f58
0033:00007ff8`5aaa2f42 80790533       cmp     byte ptr [rcx+5], 33h
0033:00007ff8`5aaa2f46 7510           jne     00007ff8`5aaa2f58
0033:00007ff8`5aaa2f48 80790633       cmp     byte ptr [rcx+6], 33h
0033:00007ff8`5aaa2f4c 750a           jne     00007ff8`5aaa2f58
0033:00007ff8`5aaa2f4e 80790737       cmp     byte ptr [rcx+7], 37h
0033:00007ff8`5aaa2f52 0f841fe2ffff   je      00007ff8`5aaa1177
0033:00007ff8`5aaa2f58 c3             ret     
```

Command lines, with some logs:
```
>wtf.exe master --max_len=1028 --runs=10000000 --target .
Seeded with 15448101250580876408
Iterating through the corpus..
Sorting through the 1 entries..
Running server on tcp://localhost:31337..
#0 cov: 0 (+0) corp: 0 (0.0b) exec/s: -nan (1 nodes) lastcov: 5.0s crash: 0 timeout: 0 cr3: 0 uptime: 5.0s
#21754 cov: 830 (+830) corp: 1 (11.0b) exec/s: 2.2k (1 nodes) lastcov: 9.0s crash: 0 timeout: 0 cr3: 21754 uptime: 15.0s
#41192 cov: 830 (+0) corp: 1 (11.0b) exec/s: 2.1k (1 nodes) lastcov: 19.0s crash: 0 timeout: 0 cr3: 41192 uptime: 25.0s
#61699 cov: 830 (+0) corp: 1 (11.0b) exec/s: 2.1k (1 nodes) lastcov: 29.0s crash: 0 timeout: 0 cr3: 61699 uptime: 35.0s
#82182 cov: 830 (+0) corp: 1 (11.0b) exec/s: 2.1k (1 nodes) lastcov: 39.0s crash: 0 timeout: 0 cr3: 82182 uptime: 45.0s
#102441 cov: 830 (+0) corp: 1 (11.0b) exec/s: 2.0k (1 nodes) lastcov: 49.0s crash: 0 timeout: 0 cr3: 102441 uptime: 55.0s
#123153 cov: 830 (+0) corp: 1 (11.0b) exec/s: 2.1k (1 nodes) lastcov: 60.0s crash: 0 timeout: 0 cr3: 123153 uptime: 1.1min
#138078 cov: 830 (+0) corp: 1 (11.0b) exec/s: 2.0k (1 nodes) lastcov: 1.2min crash: 0 timeout: 0 cr3: 138078 uptime: 1.2min
#152423 cov: 830 (+0) corp: 1 (11.0b) exec/s: 1.9k (1 nodes) lastcov: 1.3min crash: 0 timeout: 0 cr3: 152423 uptime: 1.4min
#171748 cov: 830 (+0) corp: 1 (11.0b) exec/s: 1.9k (1 nodes) lastcov: 1.5min crash: 0 timeout: 0 cr3: 171748 uptime: 1.6min
...

>wtf.exe fuzz --backend=bochscpu --name acctest1 --limit 10000000 --max_len=1028
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
acctest1: rip = 7ff85aaa2f20, end = 7ff85aaa2f58
Could not set a breakpoint at hal!HalpPerfInterrupt.
Could not set a breakpoint on hal!HalpPerfInterrupt, but carrying on..
Dialing to tcp://localhost:31337/..
#19237 cov: 830 exec/s: 1.9k lastcov: 8.0s crash: 0 timeout: 0 cr3: 19237 uptime: 10.0s
#38678 cov: 830 exec/s: 1.9k lastcov: 18.0s crash: 0 timeout: 0 cr3: 38678 uptime: 20.0s
#59195 cov: 830 exec/s: 2.0k lastcov: 28.0s crash: 0 timeout: 0 cr3: 59195 uptime: 30.0s
#79681 cov: 830 exec/s: 2.0k lastcov: 38.0s crash: 0 timeout: 0 cr3: 79681 uptime: 40.0s
#99926 cov: 830 exec/s: 2.0k lastcov: 48.0s crash: 0 timeout: 0 cr3: 99926 uptime: 50.0s
#120648 cov: 830 exec/s: 2.0k lastcov: 58.0s crash: 0 timeout: 0 cr3: 120648 uptime: 60.0s
#136372 cov: 830 exec/s: 1.9k lastcov: 1.1min crash: 0 timeout: 0 cr3: 136372 uptime: 1.2min
#150664 cov: 830 exec/s: 1.9k lastcov: 1.3min crash: 0 timeout: 0 cr3: 150664 uptime: 1.3min
#169338 cov: 830 exec/s: 1.9k lastcov: 1.5min crash: 0 timeout: 0 cr3: 169338 uptime: 1.5min
#184285 cov: 830 exec/s: 1.8k lastcov: 1.6min crash: 0 timeout: 0 cr3: 184285 uptime: 1.7min
#200383 cov: 830 exec/s: 1.8k lastcov: 1.8min crash: 0 timeout: 0 cr3: 200383 uptime: 1.8min

```

<details>
<summary>
fuzzer_acctest1.cc
</summary>

```c++
#include "backend.h"
#include "crash_detection_umode.h"
#include "targets.h"
#include <fmt/format.h>

namespace fs = std::filesystem;

namespace acctest1 {

constexpr bool LoggingOn = true;

template <typename... Args_t>
void DebugPrint(const char *Format, const Args_t &...args) {
  if constexpr (LoggingOn) {
    fmt::print("acctest1: ");
    fmt::print(Format, args...);
  }
}

bool InsertTestcase(const uint8_t *Buffer, const size_t BufferSize) {
  if (BufferSize < sizeof(uint32_t)) {
    return true;
  }

  const auto tgt = Gva_t(g_Backend->Rcx());
  const auto size = g_Backend->Rdx();
  if (!g_Backend->VirtWriteDirty(tgt, Buffer, 
              BufferSize > size ? size : BufferSize)){
    DebugPrint("Failed to write next testcase!");
    return false;
  }
  //DebugPrint("Testcase written\n");
  return true;

}

bool Init(const Options_t &Opts, const CpuState_t &) {
  //
  // Stop the test-case once we return back from the call [DeviceIoControl]
  //

  const Gva_t Rip = Gva_t(g_Backend->Rip());
  DebugPrint("rip = {:x}, end = {:x}\n", Rip, Rip + Gva_t(0x38));
  const Gva_t AfterCall = Rip + Gva_t(0x38); 
  if (!g_Backend->SetBreakpoint(AfterCall, [](Backend_t *Backend) {
        fmt::print("At the end of the function!\n");
        Backend->Stop(Ok_t());
      })) {
    DebugPrint("Failed to SetBreakpoint AfterCall\n");
    return false;
  }
  if (!g_Backend->SetBreakpoint(Rip + Gva_t(3), [](Backend_t *Backend) {
        fmt::print("At the beginnig of the function!\n");
      })) {
    DebugPrint("Failed to SetBreakpoint at the beginning\n");
    return false;
  }

  if (!SetupUsermodeCrashDetectionHooks()) {
    fmt::print("Failed to SetupUsermodeCrashDetectionHooks\n");
    return false;
  }

  return true;
}

bool Restore() { return true; }

//
// Register the target.
//

Target_t Acctest1("acctest1", Init, InsertTestcase, Restore);

} // namespace acctest1
```
</details>

We can see that:
- `Init()` is called, RIP value is correct;
- the setting of breakpoints does not lead to errors;
- `InsertTestcase()` is called on each iteration as well

However, non of the break points is really reached and there is no single userspace address in the aggregate.cov, only kernel code related to page faults.

I tried without any luck:
- regular dump and full dump;
- `g_Backend->VirtWrite`, `g_Backend->VirtWriteDirty` and even empty `InsertTestcase()`;

Any ideas? My goal is at least to see any usermode addresses in the coverage. Thanks!

PS: 
The dump is taken using kdnet -- could that cause the problems? (Pipe memory dump taking seems too slow). 
During the dump creating there was a line `[bdump] rip and gs don't match kernel/user, swapping...` but it looks in there README.md there is that like too. So, I would assume it's ok? 
Here is [target directory archive](https://mega.nz/file/74UGzLKY#o_M_vvzFAs-wy1dhqgrYthyATznu42Exux-MS1LHWV4), just in case someone wants to check the dump.

**Comment by 0vercl0k** [comment]
Thanks for such a detailed report - I have everything I need to see what's going on; will let you know :)

Cheers

**Comment by expend20** [comment]
Thank you sooo much @0vercl0k! 

I've followed your advice and now it's working and discovering new coverage. Please feel free to close this ticket whenever you like. Cheers!

One last thing I wanted to ask. Eventually the fuzzer finds the crashing code, which is represented as `mov qword ptr [0],0`. However instead of catching the crash it falls into page fault again and seems never returns to the userspace again. I would assume it should hit `ntdll!RtlDispatchException` when the `SetupUsermodeCrashDetectionHooks()` places a breakpoint, but it is not the case :( 

Here is the symbolized tace [cr3-34e60a8f1a16449fa924e5b79e37af0b.trace.syms.txt](https://github.com/0vercl0k/wtf/files/8068926/cr3-34e60a8f1a16449fa924e5b79e37af0b.trace.syms.txt)

Cheers!

**Comment by expend20** [comment]
Hello @0vercl0k,

> one thing you could try if you were willing to take another dump would be to turn off KVA shadow as it's a configuration I haven't really tested. You can turn it off running [disable-kva.cmd](https://github.com/0vercl0k/wtf/blob/main/scripts/disable-kva.cmd) in the guest VM.

Hellyeah! Worked like a charm :) 

Please let me know if I would be of any help.

Thanks!

**Comment by 0vercl0k** [comment]
Woot, I'm glad to hear that you're unblocked! I'm still interested to understand what the hell is going on with KVA shadow - will try to have a look this week!

Cheers

**Comment by 0vercl0k** [comment]
OK I took a look at this tonight and it actually makes sense. KVA shadow basically uses a set of two page tables for a process, a user one where the kernel isn't mapped and another one.

Your process is faulting, and the fault handling logic detects that it should get passed back to the user-mode exception handler in ntdll. But it currently is running with the kernel `@cr3` and as a result it needs to return back to user-mode using the user `@cr3` which triggers the swap. If you print the value of the `@cr3` it gets switched you'll see it's your process'.

I've updated the `regs.json`, `cr3` to `0x34910001`, removed the `g_Backend->SetReg(Registers_t::Cr3, 0x34910001);` off the harness, instrumented the bxcpu code to print the `@cr3` value it gets switched to and to ignore the swap. This is what you should see after:

```
Setting debug register status to zero.
Setting debug register status to zero.
acctest1: rip = 7ff85aaa2f20, end = 7ff85aaa2f58
Could not set a breakpoint at hal!HalpPerfInterrupt.
Failed to set breakpoint on HalpPerfInterrupt, but ignoring..
Running inputs\foo.bin
At the beginnig of the function!
cr3 swapped to 0xde011002
ucrash: RtlDispatchException triggered EXCEPTION_ACCESS_VIOLATION_WRITE @ 0x7ff85aaa4390
--------------------------------------------------
Run stats:
Instructions executed: 4385 (2537 unique)
          Dirty pages: 49152 bytes (0 MB)
      Memory accesses: 18029 bytes (0 MB)
#1 cov: 2537 exec/s: 1.0 lastcov: 0.0s crash: 1 timeout: 0 cr3: 0 uptime: 1.0s
```

Yay, it all makes sense :)

Cheers

**Comment by expend20** [comment]
Awesome! Thank you once again 
And let me close it

**Comment by 0vercl0k** [comment]
No worries - feel free to hit me up if you run into any other issues!
