### ISSUE TITLE
Fuzzer fails when harness uses file read/write

### ISSUE THREAD

**Issue by aceqe** [0vercl0k/wtf#87]
Hi,

I am trying a case of inserting data through the `fwrite` function, then `fseek` the pointer to the beginning of the file. Then the processing will read data from this file.

However when running through the `fwrite` function an error occurred and failed. Does bochs support emulate functions related to reading/writing data through files.?

I can example harness like this:

```
...
FILE *f_source = NULL;
fopen_s(&f_source, filename, "w+b");
char buffer[1024];
if (getenv("BREAK") != nullptr) {
    __debugbreak();
}
fwrite(buffer, 1024, 1, f_source); // insert data 
fseek(f_source, SEEK_SET, 0);
...
//process via f_source
...
```

Thanks.

**Comment by 0vercl0k** [comment]
Hello,

Could you share more details about what you are trying to achieve? I am not
sure I understand where this code is in; is it the fuzzer module or?

Cheers

**Comment by 0vercl0k** [comment]
Sounds like I had missed the title - you are correct, wtf emulates the CPU but none of the devices (disk included) so any kind of I/O will not work.

In the code you shown, you could simply set a breakpoint on `fwrite`, and populate the buffer yourself and return (skipping its code) / same for `fseek`.

Cheers

**Comment by aceqe** [comment]
Hi,

Thanks for your answer. 
I want to ask you one more question. 

Do you plan to support snapshots on VMware or Vbox? Because some drivers don't support on hyper-v.

Thanks.
