### ISSUE TITLE
Could not set a breakpoint at tlv_server!ProcessPacket.

### ISSUE THREAD

**Issue by JaneMandy** [0vercl0k/wtf#89]
Hi! I would like to ask what the hell is going on here. . I have configured the network and the symbol table is accessible. My environment is:
VMWare Windows 10 (kernel debugging) 

Setting debug register status to zero.
Setting debug register status to zero.
Could not set a breakpoint at tlv_server!ProcessPacket.
Failed to initialize the target

In addition: I think the developer should produce a more detailed document.
thanks

**Comment by 0vercl0k** [comment]
The message above means that your symbols are not configured right - `dbgeng` can't find the `tlv_server`'s symbols. Please configure your `_NT_SYMBOL_PATH` variable so that it picks up the `tlv_server.pdb` :)

Cheers

**Comment by JaneMandy** [comment]
> 上面的消息意味着您的符号配置不正确 -`dbgeng`找不到`tlv_server`' 符号。请配置您的`_NT_SYMBOL_PATH`变量，以便它获取`tlv_server.pdb`:)
> 
> 干杯
ok thanks
