### ISSUE TITLE
It seems that nt!ExGenRandom's code has changed, update the offset! HEVD

### ISSUE THREAD

**Issue by JaneMandy** [0vercl0k/wtf#91]
HEVD nt!ExGenRandom problem
Debug Address is fmt::print("Address:{}", g_Backend->VirtRead4(ExGenRandom));

1: kd> u nt!ExGenRandom
nt!ExGenRandom:
fffff8072c1239a0 48895c2420      mov     qword ptr [rsp+20h],rbx
fffff8072c1239a5 57              push    rdi

{"nt!DbgPrintEx":"0xfffff800577891a0","nt!ExGenRandom":"0xfffff8005771c9a0"}

C:\Users\test\Desktop\IOCTL>..\wtf\wtf.exe fuzz --backend=bochscpu --name hevd --limit 10000000
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.

Debug Address:10406352 //fmt::print("Address:{}", g_Backend->VirtRead4(ExGenRandom));

It seems that nt!ExGenRandom's code has changed, update the offset!
Failed to initialize the target

**Comment by 1ndahous3** [comment]
On my Windows 11 build (ntoskrnl.exe 10.0.22000.795):
```
kd> u nt!ExGenRandom+0xf3 L2
nt!ExGenRandom+0xf3:
fffff800`4a0a1e63 0fc7f2          rdrand  edx
fffff800`4a0a1e66 b800000000      mov     eax,0
```

fix for `fuzzer_*.cc`:
```
  const Gva_t ExGenRandom = Gva_t(g_Dbg.GetSymbol("nt!ExGenRandom") + 0xf3);
  if (g_Backend->VirtRead4(ExGenRandom) != 0xb8f2c70f) {
    fmt::print("It seems that nt!ExGenRandom's code has changed, update the "
               "offset!\n");
    return false;
  }
```

**Comment by 0vercl0k** [comment]
The issue with a fix like this is that it would break the demo dump that I
provide for users to try the tool easily :) A possible fix could be to scan
the function to find the `rdrand` instruction but it does feel a bit much
for not a whole lot of value IMO 🙂

Cheers

**Comment by 1ndahous3** [comment]
@0vercl0k yes, it's clear, my message is JFI and maybe someone will find that hint and not be confused seeing another instruction bytes (not 64-bit `480fc7f2 rdrand  rdx`, but 32-bit ` 0fc7f2 rdrand edx`) in latest Windows x64 kernel, so the stub can be identified with `0fc7f2` plus the next one byte via `g_Backend->VirtRead4()`.

**Comment by 0vercl0k** [comment]
Gotcha, makes sense and thanks for doing that Roman :)

Cheers
