### ISSUE TITLE
VirtTranslate failed for GVA:0xfffff80730b08c90

### ISSUE THREAD

**Issue by JaneMandy** [0vercl0k/wtf#93]
C:\Users\test\Desktop\IOCTL>..\wtf\wtf.exe fuzz --backend=bochscpu --name hevd --limit 10000 --address=tcp://192.168.70.1:31337
Initializing the debugger instance.. (this takes a bit of time)
Setting debug register status to zero.
Setting debug register status to zero.
Offset:2c1901a0
Offset:2c325d20
Offset:2c20ff00
Dialing to tcp://192.168.70.1:31337..
VirtTranslate failed for GVA:0xfffff80730b088d0
#1 cov: 6132 exec/s: 0.1 lastcov: 0.0s crash: 0 timeout: 0 cr3: 1 uptime: 17.0s
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90
VirtTranslate failed for GVA:0xfffff80730b08c90

**Comment by 0vercl0k** [comment]
Do you still need help with the above?

**Comment by JaneMandy** [comment]
sure

I'm still a beginner and I want to ask. This tool is not implemented directly through memory dump. The power failure below is not really aimed at the real application layer, right?
