### ISSUE TITLE
Thanks for the reply

### ISSUE THREAD

**Issue by JaneMandy** [0vercl0k/wtf#95]
Thanks for the reply, all the above issues have been resolved. But I would like to ask two more questions. Why (code)[https://github.com/0vercl0k/wtf/blob/main/src/wtf/fuzzer_hevd.cc#L104] What does it mean to process ExGenRandom. In addition, is Inti always called?  Thanks

**Comment by 0vercl0k** [comment]
The breakpoint on `ExGenRandom` is here to make the `ExGenRandom` function deterministic - if you use the `bochscpu` backend, the instruction `rdrand` will be deterministic so you don't really need it.

It is useful for when you use KVM/WHV backend where I don't know how to make the instruction deterministic - the best approach I found was to set a breakpoint on the `rdrand` instruction inside the `ExGenRandom` function to have deterministic outputs by emulating its 'behavior'.

Yes the `Init` function is always called [here](https://github.com/0vercl0k/wtf/blob/main/src/wtf/client.cc#L211).

Cheers

**Comment by JaneMandy** [comment]
ok, thanks for reply
