### ISSUE TITLE
nt!KiInvalidOpcodeFault 

### ISSUE THREAD

**Issue by insu123** [0vercl0k/wtf#98]
Hi.
When `sha256msg1` instruction is executed in bochscpu,  `nt!KiInvalidOpcodeFault` is called.
Can I know how to solve this problem?

thanks.

**Comment by 0vercl0k** [comment]
Hey,

If it's a Windows function invoking the instructions, there is a chance
that the caller, or whoever tests if the CPU supports the instruction and
stores a flag that says 'yes' or 'no'. And then the code doing the hash
might have a software implementation and a hardware one. If you find that
flag, you can turn it off to make it use the software path. I've run into
this once I think, with AES (??) and that's what I did.

cc @yrp604 in case he knows if sha256msg1 is supported in bochs' trunk.

Cheers

**Comment by insu123** [comment]
I modified flag and processed with software implementation.
Thank you.

And I have one more questions.
If target accesses some registry, it seems that the fuzzer doesn't work properly.
Do you have any idea to solve this problem?

**Comment by yrp604** [comment]
It's not only support inside trunk, but also the right cpu model would need to be selected during emulation. I forget where we set which cpu in particular we emulate. Otherwise what over said is exactly right -- just force a software fallback and you should be good to go.

**Comment by 0vercl0k** [comment]
Ha yeah good point forgot about the cpu model. Well, I am glad the trick worked for you as well @insu123!

Basically, registry accesses trigger at least a context switch into the `Registry` process (and maybe a file access?) and as a result isn't really supported out of the box.

In the past, I've shimmed the calls myself to do something that the application I was fuzzing was happy with (). But yeah I don't really have a generic solution, sorry!

Cheers

**Comment by insu123** [comment]
Oh Thanks for replying.
